language: node_js
node_js:
- "10"

env:
  global:
  - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
  - LOGS_DIR=/tmp/logs

addons:
  chrome: stable
  sauce_connect:
    username: ng-mentions
    access_key: 07515f712e6a-1878-0d84-01ed-d8216552

services:
  - xvfb

install:
  - yarn

cache: yarn

before_script:
  - mkdir -p $LOGS_DIR

script:
  - yarn ci && yarn api-doc:test
  - yarn global add codecov && codecov --disable=gcov -f coverage/lcov.info -F unit
  - yarn saucelabs

sudo: false
