language: node_js
node_js:
- "10"

env:
  global:
  - SAUCE_USERNAME=ng-mentions
  - SAUCE_ACCESS_KEY=07515f712e6a-1878-0d84-01ed-d8216552
  - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
  - LOGS_DIR=/tmp/logs

addons:
  chrome: stable
  sause_connect: true

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install --quiet -g gulp

install:
- npm install

script:
- npm run ci && npm run api-doc:test
- npm install -g codecov && codecov --disable=gcov -f coverage/lcov.info -F unit
- npm run saucelabs

sudo: false
